//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulsServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Card_Type
    {
        public db_Card_Type()
        {
            this.db_Card = new HashSet<db_Card>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<db_Card> db_Card { get; set; }
    }
}
