//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulsServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Card
    {
        public int id { get; set; }
        public string name { get; set; }
        public int attack { get; set; }
        public int health { get; set; }
        public int armor { get; set; }
        public int fk_ability { get; set; }
        public int fk_type { get; set; }
        public int cost { get; set; }
    
        public virtual db_Ability db_Ability { get; set; }
        public virtual db_Card_Type db_Card_Type { get; set; }
    }
}
