//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulsServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Player
    {
        public db_Player()
        {
            this.db_Player_Login = new HashSet<db_Player_Login>();
            this.db_Player_Hash = new HashSet<db_Player_Hash>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public int rank { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> fk_type { get; set; }
    
        public virtual ICollection<db_Player_Login> db_Player_Login { get; set; }
        public virtual ICollection<db_Player_Hash> db_Player_Hash { get; set; }
        public virtual db_Player_Type db_Player_Type { get; set; }
    }
}
