//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulsClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Game
    {
        public int id { get; set; }
        public int fk_player1 { get; set; }
        public int fk_player2 { get; set; }
    }
}
