//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulsClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Player_Hash
    {
        public int id { get; set; }
        public string hash { get; set; }
        public int fk_player_id { get; set; }
    
        public virtual db_Player db_Player { get; set; }
    }
}
