//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulsClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Player_Type
    {
        public db_Player_Type()
        {
            this.db_Player = new HashSet<db_Player>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int attack { get; set; }
        public int armor { get; set; }
        public int health { get; set; }
        public int fk_ability { get; set; }
    
        public virtual ICollection<db_Player> db_Player { get; set; }
    }
}
