//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulsClient.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class soulsEntities : DbContext
    {
        public soulsEntities()
            : base("name=soulsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_Card_Type> db_Card_Type { get; set; }
        public virtual DbSet<db_Ability> db_Ability { get; set; }
        public virtual DbSet<db_Card> db_Card { get; set; }
        public virtual DbSet<db_Game> db_Game { get; set; }
        public virtual DbSet<db_Player> db_Player { get; set; }
        public virtual DbSet<db_Player_Hash> db_Player_Hash { get; set; }
        public virtual DbSet<db_Player_Login> db_Player_Login { get; set; }
        public virtual DbSet<db_Player_Type> db_Player_Type { get; set; }
    }
}
